import { IS_PRODUCTION } from "./app.mjs"

export const DEVELOPMENT_ANALYSIS_APP_HOSTNAME = 'app.dev.finalytics.id'
export const PRODUCTION_ANALYSIS_APP_HOSTNAME = 'app.finalytics.id'
export const CURRENT_ANALYSIS_APP_HOSTNAME = IS_PRODUCTION
    ? PRODUCTION_ANALYSIS_APP_HOSTNAME
    : DEVELOPMENT_ANALYSIS_APP_HOSTNAME

export const DEVELOPMENT_ANALYSIS_APP_URL = `https://${DEVELOPMENT_ANALYSIS_APP_HOSTNAME}/`
export const PRODUCTION_ANALYSIS_APP_URL = `https://${PRODUCTION_ANALYSIS_APP_HOSTNAME}/`
export const CURRENT_ANALYSIS_APP_URL = `https://${CURRENT_ANALYSIS_APP_HOSTNAME}/`
